package com.example.demo.util;


import java.util.List;

// Generated 2014-10-8 14:54:14 by Hibernate Tools 3.4.0.CR1

/**
 * SystemBookProxy generated by hbm2java
 */
public class SystemBookProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4567980231758279547L;
	private String bookProxyId;
	private Integer centerId;
	private String groupId;
	private String bookProxyServer;
	private Integer bookProxyPort;
	private String bookProxyPath;
	private String bookProxyName;
	private String bookProxyRemoteServer;
	private String bookProxyUpdateServer;
	private Integer bookProxyUpdatePortStart;
	private Integer bookProxyUpdatePortEnd;
	private String bookProxyUpdateChannel;
	private String bookProxyTempChannel;
	private String bookProxyTempChannelExpire;
	private String bookProxyRegion;
	private String bookProxySynchServer;
	private String bookProxySynchRemoteServer;
	private String bookProxyCardServer;
	private String bookProxyCardRemoteServer;
	private String bookProxyRdsName;
	
	public SystemBookProxy() {
	}
	
	public String getBookProxyRdsName() {
		return bookProxyRdsName;
	}
	
	public void setBookProxyRdsName(String bookProxyRdsName) {
		this.bookProxyRdsName = bookProxyRdsName;
	}
	
	public String getBookProxyRegion() {
		return bookProxyRegion;
	}

	public void setBookProxyRegion(String bookProxyRegion) {
		this.bookProxyRegion = bookProxyRegion;
	}

	public String getBookProxyId() {
		return this.bookProxyId;
	}

	public void setBookProxyId(String bookProxyId) {
		this.bookProxyId = bookProxyId;
	}

	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getBookProxyServer() {
		return this.bookProxyServer;
	}

	public void setBookProxyServer(String bookProxyServer) {
		this.bookProxyServer = bookProxyServer;
	}

	public Integer getBookProxyPort() {
		return this.bookProxyPort;
	}

	public void setBookProxyPort(Integer bookProxyPort) {
		this.bookProxyPort = bookProxyPort;
	}

	public String getBookProxyPath() {
		return this.bookProxyPath;
	}

	public void setBookProxyPath(String bookProxyPath) {
		this.bookProxyPath = bookProxyPath;
	}

	public String getBookProxyName() {
		return bookProxyName;
	}

	public void setBookProxyName(String bookProxyName) {
		this.bookProxyName = bookProxyName;
	}

	public String getBookProxyRemoteServer() {
		return bookProxyRemoteServer;
	}

	public void setBookProxyRemoteServer(String bookProxyRemoteServer) {
		this.bookProxyRemoteServer = bookProxyRemoteServer;
	}

	public String getBookProxyUpdateServer() {
		return bookProxyUpdateServer;
	}

	public void setBookProxyUpdateServer(String bookProxyUpdateServer) {
		this.bookProxyUpdateServer = bookProxyUpdateServer;
	}

	public Integer getBookProxyUpdatePortStart() {
		return bookProxyUpdatePortStart;
	}

	public void setBookProxyUpdatePortStart(Integer bookProxyUpdatePortStart) {
		this.bookProxyUpdatePortStart = bookProxyUpdatePortStart;
	}

	public Integer getBookProxyUpdatePortEnd() {
		return bookProxyUpdatePortEnd;
	}

	public void setBookProxyUpdatePortEnd(Integer bookProxyUpdatePortEnd) {
		this.bookProxyUpdatePortEnd = bookProxyUpdatePortEnd;
	}

	public String getBookProxyUpdateChannel() {
		return bookProxyUpdateChannel;
	}

	public void setBookProxyUpdateChannel(String bookProxyUpdateChannel) {
		this.bookProxyUpdateChannel = bookProxyUpdateChannel;
	}

	public String getBookProxyTempChannel() {
		return bookProxyTempChannel;
	}

	public void setBookProxyTempChannel(String bookProxyTempChannel) {
		this.bookProxyTempChannel = bookProxyTempChannel;
	}

	public String getBookProxyTempChannelExpire() {
		return bookProxyTempChannelExpire;
	}

	public void setBookProxyTempChannelExpire(String bookProxyTempChannelExpire) {
		this.bookProxyTempChannelExpire = bookProxyTempChannelExpire;
	}
	
	public String getBookProxySynchServer() {
		return bookProxySynchServer;
	}

	public void setBookProxySynchServer(String bookProxySynchServer) {
		this.bookProxySynchServer = bookProxySynchServer;
	}

	public String getBookProxySynchRemoteServer() {
		return bookProxySynchRemoteServer;
	}

	public void setBookProxySynchRemoteServer(String bookProxySynchRemoteServer) {
		this.bookProxySynchRemoteServer = bookProxySynchRemoteServer;
	}

	public String getBookProxyCardServer() {
		return bookProxyCardServer;
	}

	public void setBookProxyCardServer(String bookProxyCardServer) {
		this.bookProxyCardServer = bookProxyCardServer;
	}

	public String getBookProxyCardRemoteServer() {
		return bookProxyCardRemoteServer;
	}

	public void setBookProxyCardRemoteServer(String bookProxyCardRemoteServer) {
		this.bookProxyCardRemoteServer = bookProxyCardRemoteServer;
	}
	
	public String getUrl() {

		if (bookProxyPort == null) {
			bookProxyPort = 80;
		}
		if (bookProxyPath == null) {
			bookProxyPath = "/pos3Server";
		}
		if(this.bookProxyRegion != null && this.bookProxyRegion.equals("青岛")){
			return "http://" + bookProxyRemoteServer + ":" + bookProxyPort + "/"
			+ bookProxyPath;
		}else{
			return "http://" + bookProxyServer + ":" + bookProxyPort + "/"
					+ bookProxyPath;
		}
	}

	
	public static SystemBookProxy getBookProxy(
            List<SystemBookProxy> systemBookProxys, Integer centerId) {
		for(SystemBookProxy data: systemBookProxys){
			if(data.getCenterId().equals(centerId)){
				return data;
			}
		}
		return null;
	}
}
